spring:
#  cloud:
#    gateway:
#      routes:
#        - id: rewritepath_route
#          uri: https://tieba.baidu.com
#          predicates:
#            - Path=/a/p/**
#          filters:
#            - RewritePath=/a(?<segment>/?.*), $\{segment}
#        - id: anti_tamper
#          uri: http://localhost:8081
#          predicates:
#            - Path=/a/b/**
#          filters:
#            - RewritePath=/a(?<segment>/?.*), $\{segment}
#            - AntiTamper=x-tamper,adbfzfa


  main:
    allow-bean-definition-overriding: true
server:
  port: 31001